
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Thu Apr 10 22:59:07 PDT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_STRUCTDEF = 60;
  public static final int T_ID = 71;
  public static final int T_AMPERSAND = 2;
  public static final int T_MOD = 42;
  public static final int T_FALSE = 26;
  public static final int T_ID_U = 70;
  public static final int T_ENDL = 22;
  public static final int T_FLOAT = 27;
  public static final int T_AUTO = 65;
  public static final int T_NULLPTR = 46;
  public static final int T_BOOL = 7;
  public static final int T_COUT = 17;
  public static final int T_SLASH = 57;
  public static final int T_GT = 30;
  public static final int T_STATIC = 59;
  public static final int T_DOT = 20;
  public static final int T_INT = 33;
  public static final int T_LTE = 39;
  public static final int T_WHILE = 63;
  public static final int T_CIN = 11;
  public static final int T_SEMI = 55;
  public static final int T_CHAR_LITERAL = 66;
  public static final int T_BREAK = 8;
  public static final int T_COLONCOLON = 13;
  public static final int T_GTE = 31;
  public static final int T_LT = 38;
  public static final int T_MINUSMINUS = 41;
  public static final int T_SIZEOF = 56;
  public static final int T_RBRACE = 51;
  public static final int T_MINUS = 40;
  public static final int T_RPAREN = 54;
  public static final int T_NEW = 44;
  public static final int T_LBRACE = 35;
  public static final int T_LPAREN = 37;
  public static final int T_INT_LITERAL = 68;
  public static final int T_NEQ = 43;
  public static final int T_AND = 3;
  public static final int T_COLON = 12;
  public static final int T_BAR = 6;
  public static final int T_TYPEDEF = 62;
  public static final int T_DECLTYPE = 19;
  public static final int T_TRUE = 61;
  public static final int T_CARET = 9;
  public static final int EOF = 0;
  public static final int T_PLUS = 49;
  public static final int T_FUNCTION = 29;
  public static final int T_CHAR = 10;
  public static final int T_DELETE = 18;
  public static final int T_ASSIGN = 5;
  public static final int T_OSTREAM = 48;
  public static final int T_STAR = 58;
  public static final int T_STR_LITERAL = 69;
  public static final int T_RBRACKET = 52;
  public static final int T_VOID = 64;
  public static final int T_EXTERN = 25;
  public static final int error = 1;
  public static final int T_ELSE = 21;
  public static final int T_FLOAT_LITERAL = 67;
  public static final int T_CONTINUE = 16;
  public static final int T_ARROW = 4;
  public static final int T_ISTREAM = 34;
  public static final int T_CONST = 15;
  public static final int T_PLUSPLUS = 50;
  public static final int T_RETURN = 53;
  public static final int T_EQU = 23;
  public static final int T_EXIT = 24;
  public static final int T_NOT = 45;
  public static final int T_LBRACKET = 36;
  public static final int T_FUNCPTR = 28;
  public static final int T_OR = 47;
  public static final int T_COMMA = 14;
  public static final int T_IF = 32;
}

